# Generated by Django 5.2 on 2025-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=39, unique=True, verbose_name='Username')),
                ('repo_count', models.IntegerField(default=0, verbose_name='Количество репозиториев')),
                ('popular_languages', models.JSONField(default=list, verbose_name='Популярные языки')),
                ('last_commit_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
